version: '3.9'
services:
    database:
        image: mongo
        container_name: mongodb_container
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: badpassword
        ports:
            - 27017:27017
        volumes:
              - order_data_container:/data/db

volumes:
  order_data_container: