name: coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    # Runs a set of commands using the runners shell
    - name: Coverage
      run: |
        make coverage
        curl -Os https://uploader.codecov.io/latest/linux/codecov 
        chmod +x codecov 
        ./codecov
