name: Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go- 

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    # Runs a set of commands using the runners shell
    - name: Coverage
      run: |
        make coverage
        curl -Os https://uploader.codecov.io/latest/linux/codecov 
        chmod +x codecov 
        ./codecov
